apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent
spec:
  template:
    spec:
      containers:
        - name: agent
          env:
            - name: LLM_API_KEY
              valueFrom:
                secretKeyRef:
                  name: llm-credentials
                  key: LLM_API_KEY
            - name: LLAMA_STACK_BASE_URL
              value: http://llamastack-demo-service:8321/v1
            - name: LLAMA_STACK_MODEL
              value: vllm-inference/llama-32-3b-instruct
            - name: STACK_VECTOR_STORE_NAME
              value: agent-kb
            - name: STACK_EMBEDDING_MODEL
              value: sentence-transformers/nomic-ai/nomic-embed-text-v1.5
            - name: TRUSTYAI_SHIELD_ID
              value: built-in-detector
            - name: TRUSTYAI_ORCHESTRATOR_URL
              value: https://guardrails-service.my-first-model.svc:8032
            - name: MLFLOW_TRACKING_URI
              value: https://mlflow.redhat-ods-applications.svc:8443
            - name: MLFLOW_TRACKING_AUTH
              value: kubernetes-namespaced
            - name: MLFLOW_TRACKING_INSECURE_TLS
              value: "true"
            - name: MLFLOW_WORKSPACE
              value: agent-azuresdk-demo-ogx-native
            - name: MLFLOW_UI_URL
              value: https://rh-ai.apps.ocp.9jkcd.sandbox3005.opentlc.com/mlflow/#/?workspace=agent-azuresdk-demo-ogx-native
            - name: MLFLOW_EXPERIMENT
              value: agent-azuresdk-demo-ogx-native
            - name: MLFLOW_TRACING_ENABLED
              value: "true"
