apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: agent-azuresdk-demo-main
resources:
  - ../../base
# App release knob — change ONLY newTag after Tekton builds a new image
images:
  - name: agent
    newName: image-registry.openshift-image-registry.svc:5000/agent-azuresdk-demo-main/agent
    newTag: v0.1.0
