apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agent-azuresdk-demo-ogx
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/part-of: agent-azuresdk-demo
spec:
  project: default
  source:
    repoURL: https://github.com/maschind/agent-azuresdk-demo.git
    targetRevision: ogx
    path: deploy/overlays/ogx
  destination:
    server: https://kubernetes.default.svc
    namespace: agent-azuresdk-demo-ogx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
